#!/bin/bash
git=".git"
if [ ! $1 = "-h" ] && [ ! $1 = "--help" ] && [ ! $1 = "" ] ; then
	for f in * ; do
		if [ -d $f ] ; then
			pushd $f > /dev/null
			if [ -e $git ] ; then
				printf "$f: git $1\n"
				git $1 $2 $3 $4 $5 $6 $7 $8 $9
				printf "\n"
			fi
			popd > /dev/null
		fi
	done
else
  printf "usage: agit.sh  <command> [<args>]\n\n"
  printf "This script searches subdirectories and then executes a git command\n"
  printf "if it is a git repository.\n\n"
  printf "see 'git help' for more about git commands\n"
fi
